= ExtremeCloud IQ OpenAPI Specification
:toc:

== Introduction

https://extremecloudiq.com/login[ExtremeCloud IQ] is a cloud-based solution offered by https://www.extremenetworks.com/[Extreme Networks] that provides centralized management and control for networking devices, including access points (AP), switches,and routers.

ExtremeCloud IQ OpenAPI specification is a comprehensive and powerful OpenAPI that enables developers to integrate with the ExtremeCloud IQ cloud-managed network management platform.

== What it can do

With the ExtremeCloud IQ OpenAPI specification, developers can leverage a wide range of RESTful APIs to interact with the platform and perform various tasks such as provisioning and configuration, monitoring and reporting, and troubleshooting.

Developers can use the ExtremeCloud IQ OpenAPI specification to build custom applications, automate network management tools, and integrate with other systems.

== How to use the API

ExtremeCloud IQ OpenAPI specification is based on the latest https://spec.openapis.org/oas/latest.html[OpenAPI 3.x standard], which allows for easy and standardized communication between different systems and programming languages.

ExtremeCloud IQ OpenAPI Specification provides a well-documented and consistent interface for developers to interact with the ExtremeCloud IQ platform, making it simple and efficient to build integrations and applications that extend the capabilities of the platform.

Please check the below links for the documentation and tools we provided:

* https://developer.extremecloudiq.com/[ExtremeCloud IQ Developer portal]
* https://api.extremecloudiq.com/swagger-ui/index.html[Swagger UI]
* https://developer.extremecloudiq.com/documentation/[API Documentation & Tutorial]

== Releases

Normally ExtremeCloud IQ OpenAPI will release every 1-2 months, please check below links for the historical release notes and OpenAPI specifications.

* https://developer.extremecloudiq.com/releases/[Release Notes]
* https://github.com/extremenetworks/ExtremeCloudIQ-OpenAPI-Specification/releases[Release History]
